apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i-build-and-push
spec:
  params:
    - name: IMAGE_REGISTRY
      description: The container image registry
    - name: IMAGE_REPO
      description: The container image repository
    - name: IMAGE_TAG
      default: "latest"
      description: The container image tag
  workspaces:
    - name: source
  steps:
    - name: s2i-build
      image: quay.io/openshift/origin-source-to-image:latest
      script: |
        s2i build /workspace/source quay.io/redhat/java-s2i tektonci-app
    - name: push-image
      image: quay.io/containers/podman:v3.0.1
      script: |
        echo "$TOKEN" | podman login $(params.IMAGE_REGISTRY) -u $USERNAME --password-stdin
        podman push tektonci-app $(params.IMAGE_REGISTRY)/$(params.IMAGE_REPO):$(params.IMAGE_TAG)
